// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSdzqfRtaMRhXpXj0WwjM3Zx4l3ydmtX0',
    appId: '1:524829583316:android:456a92fcb8ebab24a41841',
    messagingSenderId: '524829583316',
    projectId: 'deliveryapp-375dd',
    storageBucket: 'deliveryapp-375dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7o5BICFCHcBNmn61bgrFdeb0FEY8or8',
    appId: '1:524829583316:ios:07f5c53516cc4ceca41841',
    messagingSenderId: '524829583316',
    projectId: 'deliveryapp-375dd',
    storageBucket: 'deliveryapp-375dd.firebasestorage.app',
    androidClientId: '524829583316-gr0vd9jj4o6b9dg42hg4e1leg4tqqjvs.apps.googleusercontent.com',
    iosClientId: '524829583316-11vka9cgqpu71gq0apj2ua9fabrs8bsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );
}
